### ISSUE TITLE
reorganize OpenLDAP packaging section

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/documentation#4]
We could have a more generic section at the beginning, explaining the concepts, the content of the packages,...

**Comment by coudot** [comment]
Some ideas for table of contents:

# LDAP Tool Box documentation

## Presentation
LTB project is...
* OpenLDAP LTB packages
* Monitoring scripts
* ...

## Install OpenLDAP LTB
* Debian/Ubuntu
* RedHat/CentOS

## Administration
* slapd-cli manual
* Logs analysis

## Monitor your directory
* Nagios
* Cacti

## Scripts

## How to
